name: Scheduled Deploy

on:
  schedule:
    - cron: '0 5 8 8 *'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy on Vercel
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"